import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CssBaseline, ThemeProvider } from '@mui/material';
import theme from '../src/theme';
import Header from "./header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Join FaceVsFace Polling and compete in exciting face-off challenges to win money and prizes every week. Our platform offers users the chance to participate in head-to-head polls, vote for their favorites, and see who comes out on top. With weekly winners and grand prizes, FaceVsFace Polling is your go-to destination for competitive fun and rewards in India. Sign up today and start winning big!" />
        <meta name="keywords" content="face vs face, face-to-face polling, win money, weekly prizes, contests, head-to-head polls, competitive challenges, India, online polling, vote to win, cash prizes, rewards, participate in polls, join the challenge, exciting competitions, voting platform, prize giveaways, weekly winners, win cash, fun contests, faceoff, competitive fun, vote and win, online contests, prize competitions, weekly cash prizes, win rewards, polling platform, challenge your friends, voting contests, win big, head-to-head competitions, Indian polls, voting challenges, join and win, competitive polls, online faceoffs, poll and win, win every week, contest platform, grand prizes, faceoff challenges, win contests, fun polling, weekly faceoff, India contests, poll to win, win money online, prize draws, weekly challenges, exciting prizes, cash giveaways, Indian competitions, vote for prizes, weekly rewards, win cash contests, participate and win, online challenges, Indian faceoffs, vote for cash, weekly giveaways, win rewards online, prize-winning platform, Indian polls online, faceoff competitions, weekly winners list, online prize contests, win big in India, cash prize challenges, weekly faceoff contests, join polls, win contests every week, prize competitions in India, voting for cash, exciting online competitions, win every week in India, contest challenges, prize platform, vote and win money, online weekly contests, prize draws in India, weekly cash challenges, fun competitions, win big every week, participate in Indian contests, faceoff polling, Indian prize challenges, weekly prize draws, win money in India, online vote to win, join and win cash, Indian online polls, weekly online challenges, faceoff prize contests, win every week online, Indian voting contests, join faceoffs, win money every week in India, participate in faceoffs, online prize challenges, weekly cash rewards, vote to win cash, Indian contest platform, exciting weekly prizes, win weekly challenges, prize contests in India, win rewards every week, join polling challenges, Indian online competitions, weekly faceoff challenges, win cash every week, participate in Indian faceoff, prize-winning contests, faceoff polling platform, online prize draws, weekly Indian challenges, win prizes every week, online voting challenges, Indian cash prize contests, weekly contests in India, join and win contests, weekly prize challenges, online faceoff competitions, win every week cash, vote and win prizes, Indian weekly challenges, join contests in India, faceoff cash challenges, weekly prize competitions, online voting platform, prize challenges in India, win every week challenges, Indian prize draws, vote and win every week, weekly Indian contests, join and win weekly, faceoff prize challenges, online contests in India, win money weekly, weekly prize competitions in India, vote for weekly prizes, join Indian faceoffs, weekly online competitions in India, faceoff challenges in India, win every week in contests, Indian prize competitions, online weekly prize draws, win money in Indian contests, weekly faceoff competitions in India, prize-winning contests every week, Indian voting competitions, weekly online prize challenges, join and win weekly prizes, Indian cash prize competitions, weekly Indian prize draws, participate in weekly faceoffs, online voting contests in India, weekly prize-winning contests, join weekly Indian challenges, win weekly online, weekly prize-winning competitions in India" />
        <meta name="robots" content="index, follow" />
        <meta name="author" content="FaceVsFace Polling" />
        <meta name="geo.region" content="IN" />
        <meta name="geo.placename" content="India" />
        <meta name="geo.position" content="20.5937;78.9629" />
        <meta name="ICBM" content="20.5937, 78.9629" />
        <meta property="og:title" content="FaceVsFace Polling - Win Money Every Week!" />
        <meta property="og:description" content="Join FaceVsFace Polling and compete in exciting face-off challenges to win money and prizes every week. Our platform offers users the chance to participate in head-to-head polls, vote for their favorites, and see who comes out on top. With weekly winners and grand prizes, FaceVsFace Polling is your"/>
      <body className={inter.className}>        
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Header/>
          {children}
        </ThemeProvider></body>
    </html>
  );
}
